// Catálogos oficiales extraídos de CAV v1.0 - HGR No. 1 (OOAD Michoacán)

export interface CatalogOption {
  code: string;
  label: string;
}

export const CAV_PARKING_LOTS: readonly CatalogOption[] = [
  { code: "1", label: "BASE" },
  { code: "2", label: "CONFIANZA" },
  { code: "3", label: "VISITANTES" },
] as const;

export const CAV_SHIFTS: readonly CatalogOption[] = [
  { code: "M", label: "Matutino" },
  { code: "V", label: "Vespertino" },
  { code: "N", label: "Nocturno" },
  { code: "A", label: "Acumulada" },
] as const;

export const CAV_HGR1_UNIT_CODE = "170501";

export const CAV_AREAS: readonly CatalogOption[] = [
  { code: "51201", label: "Servs orient y quejas" },
  { code: "100902", label: "Servicios Admvos En Unidades M" },
  { code: "130100", label: "Depto Construc-Planeac Inmobil" },
  { code: "141901", label: "Transportes Terrestres -Ambula" },
  { code: "141902", label: "Comunicaciones Electricas" },
  { code: "142901", label: "Servs Basicos" },
  { code: "142902", label: "Residencia De Conservacion" },
  { code: "142905", label: "Servicio de Limpieza e Higiene" },
  { code: "150901", label: "Almacen De Unidad Medica" },
  { code: "200200", label: "Direccion de la Unidad Médica" },
  { code: "200201", label: "Jefatura de Cirugía / Especialidades" },
  { code: "200202", label: "Jefatura de Medicina Interna" },
  { code: "200203", label: "Farmacia" },
  { code: "200204", label: "Lab Citología Exfoliativa" },
  { code: "200205", label: "Laboratorio Clínico" },
  { code: "200206", label: "Atención Médica Continúa" },
  { code: "200207", label: "Gabinete De Rayos X" },
  { code: "200208", label: "Consulta Dental" },
  { code: "200209", label: "Nutrición y Dietética" },
  { code: "200210", label: "Banco de Sangre" },
  { code: "200211", label: "Consulta a Donadores" },
  { code: "200215", label: "Medicina Fisica y Rehabilitaci" },
  { code: "200216", label: "Anatomía Patológica" },
  { code: "200217", label: "Hospitalización" },
  { code: "200218", label: "Urgencias" },
  { code: "200219", label: "Quirofanos" },
  { code: "200220", label: "Terapia Intensiva" },
  { code: "200221", label: "Tococírugia" },
  { code: "200222", label: "Pediatría" },
  { code: "200223", label: "Consulta De Especialidades" },
  { code: "200224", label: "Gabinete de Electrodiagnostico" },
  { code: "200227", label: "Hemodialisis" },
  { code: "200240", label: "Terapia Psicologica" },
  { code: "200242", label: "Protesis y Ortesis" },
  { code: "200244", label: "Terapia Física" },
  { code: "200246", label: "Tomografia Axial Computarizada" },
  { code: "200260", label: "UnidCuidadosIntensivNeonatales" },
  { code: "200263", label: "Centro de Mezclas" },
  { code: "200901", label: "Jefatura de Enfermería" },
  { code: "200902", label: "Trabajo Social" },
  { code: "200903", label: "Lavanderia Propia de la Unidad" },
  { code: "200905", label: "Traslado De Pacientes" },
  { code: "200907", label: "Ctral de Equipos y Esterilizac" },
  { code: "200908", label: "Traspaso Costo Atn Med IMSS" },
  { code: "230201", label: "Medicina Del Trabajo Anal Y Ev" },
  { code: "230204", label: "Serv de Prev yProm de la Salud" },
  { code: "230903", label: "Divisiones De Salud En El Trab" },
  { code: "230904", label: "Servs Infor-Asesoria-Capacit-S" },
  { code: "250901", label: "Coordinación Clínica de Educación" },
  { code: "250902", label: "Biblioteca Medica Biblio Trab" },
  { code: "250903", label: "Educacion Continua" },
  { code: "250904", label: "Pasantes En Servicio Social Pr" },
  { code: "250905", label: "Postgrado De Enfermeria" },
  { code: "250906", label: "Internado De Pregrado" },
  { code: "250908", label: "Postgrado De Medicina" },
  { code: "250909", label: "Formacion Profesores P-Ensenan" },
  { code: "250910", label: "Lic Enfer Sist Univer Abierta" },
  { code: "2H0210", label: "Promoción de la Salud" },
  { code: "2H0220", label: "Prog Integ de Salud PREVENIMSS" },
  { code: "2H0230", label: "Prog Esp de Planificacion Fam" },
  { code: "2H0240", label: "Prot Anticonc Gen y Salud" },
  { code: "2H0250", label: "Atn Materna y Perinatal" },
  { code: "2J0910", label: "Area Inf Med y Archivo Clinico" },
  { code: "610200", label: "Serv Admvos Presp Cont UMed" },
  { code: "999998", label: "CENTRO DE COSTOS DUMMY" },
] as const;

export const CAV_VEHICLE_MODELS: readonly CatalogOption[] = [
  { code: "160", label: "Acura) RDX" },
  { code: "357", label: "Acura) NSX" },
  { code: "225", label: "Acura) MDX" },
  { code: "271", label: "Acura) ILX" },
  { code: "279", label: "Acura) TLX" },
  { code: "290", label: "Alfa) Romeo Giulietta" },
  { code: "326", label: "Alfa) Romeo MiTo" },
  { code: "361", label: "Alfa) Romeo 4C" },
  { code: "346", label: "Alfa) Romeo Giulia" },
  { code: "318", label: "Alfa) Romeo Stelvio" },
  { code: "159", label: "Audi) A5" },
  { code: "267", label: "Audi) A7" },
  { code: "307", label: "Audi) Q7" },
  { code: "85", label: "Audi) A3" },
  { code: "330", label: "Audi) R8" },
  { code: "342", label: "Audi) e-tron" },
  { code: "270", label: "Audi) A6" },
  { code: "183", label: "Audi) A4" },
  { code: "339", label: "Audi) Q3" },
  { code: "184", label: "Audi) Q8" },
  { code: "257", label: "Audi) A1" },
  { code: "311", label: "Audi) A8" },
  { code: "256", label: "Audi) A3 Sedan" },
  { code: "98", label: "Audi) Q5" },
  { code: "123", label: "Audi) Q2" },
  { code: "366", label: "Audi) TT" },
  { code: "147", label: "BAIC) D20" },
  { code: "254", label: "BAIC) BJ40" },
  { code: "173", label: "BAIC) X25" },
  { code: "262", label: "BAIC) BJ20" },
  { code: "281", label: "BAIC) X65" },
  { code: "229", label: "BAIC) X35" },
  { code: "371", label: "Bentley) Continental Flying Spur" },
  { code: "351", label: "Bentley) Bentayga" },
  { code: "367", label: "Bentley) Continental GT" },
  { code: "284", label: "BMW) Z4" },
  { code: "276", label: "BMW) X7" },
  { code: "285", label: "BMW) i3" },
  { code: "206", label: "BMW) Serie 5" },
  { code: "129", label: "BMW) X2" },
  { code: "313", label: "BMW) Serie 7" },
  { code: "203", label: "BMW) X6" },
  { code: "194", label: "BMW) Serie 2" },
  { code: "140", label: "BMW) Serie 1" },
  { code: "101", label: "BMW) X3" },
  { code: "327", label: "BMW) Serie 8" },
  { code: "94", label: "BMW) X1" },
  { code: "121", label: "BMW) Serie 3" },
  { code: "368", label: "BMW) Serie 6" },
  { code: "180", label: "BMW) Serie 4" },
  { code: "336", label: "BMW) i8" },
  { code: "110", label: "BMW) X5" },
  { code: "158", label: "BMW) X4" },
  { code: "251", label: "Buick) Envision" },
  { code: "186", label: "Buick) Enclave" },
  { code: "138", label: "Buick) Encore" },
  { code: "369", label: "Buick) Regal" },
  { code: "329", label: "Cadillac) ATS" },
  { code: "255", label: "Cadillac) XT5" },
  { code: "215", label: "Cadillac) XT4" },
  { code: "233", label: "Cadillac) Escalade" },
  { code: "343", label: "Cadillac) CTS" },
  { code: "362", label: "Chevrolet) S10" },
  { code: "31", label: "Chevrolet) Spark" },
  { code: "241", label: "Chevrolet) Camaro" },
  { code: "143", label: "Chevrolet) Blazer" },
  { code: "231", label: "Chevrolet) Express" },
  { code: "249", label: "Chevrolet) Cruze" },
  { code: "24", label: "Chevrolet) Cavalier" },
  { code: "17", label: "Chevrolet) Trax" },
  { code: "320", label: "Chevrolet) Corvette" },
  { code: "8", label: "Chevrolet) Beat" },
  { code: "6", label: "Chevrolet) Beat Notchback" },
  { code: "111", label: "Chevrolet) Equinox" },
  { code: "131", label: "Chevrolet) Suburban" },
  { code: "373", label: "Chevrolet) Sonic Hatchback" },
  { code: "375", label: "Chevrolet) Matiz" },
  { code: "2", label: "Chevrolet) Aveo" },
  { code: "139", label: "Chevrolet) Colorado" },
  { code: "82", label: "Chevrolet) Tornado" },
  { code: "344", label: "Chevrolet) Volt" },
  { code: "72", label: "Chevrolet) Silverado" },
  { code: "335", label: "Chevrolet) Bolt" },
  { code: "187", label: "Chevrolet) Traverse" },
  { code: "356", label: "Chevrolet) Camaro Convertible" },
  { code: "190", label: "Chevrolet) Tahoe" },
  { code: "67", label: "Chevrolet) Cheyenne" },
  { code: "372", label: "Chevrolet) Chevy" },
  { code: "277", label: "Chevrolet) Malibu" },
  { code: "354", label: "Chevrolet) Sonic" },
  { code: "192", label: "Chrysler) Caravan" },
  { code: "204", label: "Chrysler) Pacifica" },
  { code: "358", label: "Chrysler) 300C" },
  { code: "175", label: "Dodge) Neon" },
  { code: "113", label: "Dodge) Journey" },
  { code: "286", label: "Dodge) Vision" },
  { code: "228", label: "Dodge) Challenger" },
  { code: "25", label: "Dodge) Attitude" },
  { code: "124", label: "Dodge) Charger" },
  { code: "244", label: "Dodge) Durango" },
  { code: "312", label: "Fiat) 500L" },
  { code: "84", label: "Fiat) Mobi" },
  { code: "181", label: "Fiat) Palio Adventure" },
  { code: "283", label: "Fiat) 500" },
  { code: "222", label: "Fiat) Ducato" },
  { code: "102", label: "Fiat) Uno" },
  { code: "359", label: "Ford) Focus ST" },
  { code: "205", label: "Ford) Fusion" },
  { code: "209", label: "Ford) F-550" },
  { code: "133", label: "Ford) Fiesta Sedan" },
  { code: "178", label: "Ford) Edge" },
  { code: "135", label: "Ford) Explorer" },
  { code: "171", label: "Ford) Expedition" },
  { code: "162", label: "Ford) F-450" },
  { code: "263", label: "Ford) Fusion Hybrid" },
  { code: "219", label: "Ford) Figo Hatchback" },
  { code: "145", label: "Ford) Mustang" },
  { code: "212", label: "Ford) F-250" },
  { code: "301", label: "Ford) Focus Sedan" },
  { code: "18", label: "Ford) Figo Sedan" },
  { code: "80", label: "Ford) F-150" },
  { code: "66", label: "Ford) Lobo" },
  { code: "363", label: "Ford) Fiesta Hatchback" },
  { code: "88", label: "Ford) Transit" },
  { code: "347", label: "Ford) Crown Victoria - Police Interceptor" },
  { code: "87", label: "Ford) F-350" },
  { code: "38", label: "Ford) Ranger" },
  { code: "350", label: "Ford) Focus Hatch" },
  { code: "349", label: "Ford) Escape Hybrid" },
  { code: "79", label: "Ford) Escape" },
  { code: "74", label: "Ford) EcoSport" },
  { code: "333", label: "Ford) Fiesta ST" },
  { code: "128", label: "GMC) Terrain" },
  { code: "220", label: "GMC) Yukon" },
  { code: "151", label: "GMC) Sierra" },
  { code: "165", label: "GMC) Acadia" },
  { code: "28", label: "Honda) City" },
  { code: "42", label: "Honda) Civic" },
  { code: "89", label: "Honda) Fit" },
  { code: "59", label: "Honda) BR-V" },
  { code: "15", label: "Honda) HR-V" },
  { code: "142", label: "Honda) Pilot" },
  { code: "114", label: "Honda) Odyssey" },
  { code: "196", label: "Honda) Insight" },
  { code: "11", label: "Honda) CR-V" },
  { code: "103", label: "Honda) Accord" },
  { code: "208", label: "Hyundai) Santa Fe" },
  { code: "46", label: "Hyundai) Accent Sedan" },
  { code: "295", label: "Hyundai) Sonata" },
  { code: "245", label: "Hyundai) Santa Fe 7 pasajeros" },
  { code: "93", label: "Hyundai) Accent Hatchback" },
  { code: "156", label: "Hyundai) Starex" },
  { code: "61", label: "Hyundai) Tucson" },
  { code: "136", label: "Hyundai) Ioniq" },
  { code: "96", label: "Hyundai) Elantra" },
  { code: "68", label: "Hyundai) Grand i10" },
  { code: "44", label: "Hyundai) Grandi i10 Sedán" },
  { code: "39", label: "Hyundai) Creta" },
  { code: "316", label: "Infiniti) Q70" },
  { code: "272", label: "Infiniti) QX80" },
  { code: "260", label: "Infiniti) Q50" },
  { code: "337", label: "Infiniti) QX30" },
  { code: "315", label: "Infiniti) Q60" },
  { code: "227", label: "Infiniti) QX50" },
  { code: "302", label: "Infiniti) QX70" },
  { code: "213", label: "Infiniti) QX60" },
  { code: "176", label: "Isuzu) 300" },
  { code: "177", label: "Isuzu) 100" },
  { code: "268", label: "Isuzu) ELF 200" },
  { code: "127", label: "JAC) Sei 2" },
  { code: "200", label: "JAC) Frison" },
  { code: "144", label: "JAC) Sei 3" },
  { code: "236", label: "JAC) Sei 7" },
  { code: "248", label: "JAC) J4" },
  { code: "288", label: "JAC) Sei 4" },
  { code: "364", label: "Jaguar) XF" },
  { code: "340", label: "Jaguar) F-Type" },
  { code: "314", label: "Jaguar) XE" },
  { code: "345", label: "Jaguar) i-Pace" },
  { code: "293", label: "Jaguar) E-Pace" },
  { code: "280", label: "Jaguar) F-Pace" },
  { code: "117", label: "Jeep) Compass" },
  { code: "108", label: "Jeep) Renegade" },
  { code: "232", label: "Jeep) Cherokee" },
  { code: "99", label: "Jeep) Grand Cherokee" },
  { code: "226", label: "Jeep) Gladiator" },
  { code: "75", label: "Jeep) Wrangler" },
  { code: "32", label: "KIA) Soul" },
  { code: "52", label: "KIA) Sorento" },
  { code: "29", label: "KIA) Rio Hatchback" },
  { code: "90", label: "KIA) Sedona" },
  { code: "148", label: "KIA) Niro" },
  { code: "16", label: "KIA) Sportage" },
  { code: "239", label: "KIA) Stinger" },
  { code: "7", label: "KIA) Rio Sedan" },
  { code: "13", label: "KIA) Forte Sedan" },
  { code: "115", label: "KIA) Forte Hatchback" },
  { code: "182", label: "KIA) Optima" },
  { code: "294", label: "Land) Rover Discovery" },
  { code: "275", label: "Land) Rover Discovery Sport" },
  { code: "303", label: "Lincoln) MKZ Hybrid" },
  { code: "304", label: "Lincoln) Aviator" },
  { code: "214", label: "Lincoln) Navigator" },
  { code: "207", label: "Lincoln) MKC" },
  { code: "253", label: "Lincoln) Corsair" },
  { code: "265", label: "Lincoln) Nautilus" },
  { code: "317", label: "Lincoln) Continental" },
  { code: "289", label: "Lincoln) MKZ" },
  { code: "45", label: "Mazda) 3 Hatchback" },
  { code: "141", label: "Mazda) CX-9" },
  { code: "120", label: "Mazda) CX-30" },
  { code: "36", label: "Mazda) CX-3" },
  { code: "164", label: "Mazda) 6" },
  { code: "19", label: "Mazda) 3 Sedan" },
  { code: "22", label: "Mazda) CX-5" },
  { code: "57", label: "Mazda) 2 Sedan" },
  { code: "161", label: "Mazda) MX-5" },
  { code: "109", label: "Mazda) 2 Hatchback" },
  { code: "328", label: "Mercedes-AMG) GT" },
  { code: "250", label: "Mercedes-Benz) Clase V" },
  { code: "261", label: "Mercedes-Benz) GLS" },
  { code: "266", label: "Mercedes-Benz) Clase B" },
  { code: "292", label: "Mercedes-Benz) CLS" },
  { code: "134", label: "Mercedes-Benz) GLA" },
  { code: "296", label: "Mercedes-Benz) Clase S" },
  { code: "71", label: "Mercedes-Benz) Sprinter" },
  { code: "122", label: "Mercedes-Benz) Clase C" },
  { code: "65", label: "Mercedes-Benz) GLC" },
  { code: "198", label: "Mercedes-Benz) Clase E" },
  { code: "305", label: "Mercedes-Benz) SLC" },
  { code: "112", label: "Mercedes-Benz) GLE" },
  { code: "211", label: "Mercedes-Benz) Clase G" },
  { code: "217", label: "Mercedes-Benz) Clase A" },
  { code: "126", label: "Mercedes-Benz) CLA" },
  { code: "252", label: "MINI) Convertible" },
  { code: "92", label: "MINI) Cooper 3 puertas" },
  { code: "259", label: "MINI) Clubman" },
  { code: "172", label: "MINI) Cooper 5 puertas" },
  { code: "152", label: "MINI) Countryman" },
  { code: "240", label: "Mitsubishi) Montero Sport" },
  { code: "55", label: "Mitsubishi) L200" },
  { code: "106", label: "Mitsubishi) Mirage G4" },
  { code: "278", label: "Mitsubishi) Outlander PHEV" },
  { code: "338", label: "Mitsubishi) Montero" },
  { code: "76", label: "Mitsubishi) Mirage" },
  { code: "167", label: "Mitsubishi) Outlander" },
  { code: "323", label: "Mitsubishi) Montero Limited" },
  { code: "174", label: "Mitsubishi) Eclipse Cross" },
  { code: "325", label: "Nissan) Armada" },
  { code: "299", label: "Nissan) LEAF" },
  { code: "298", label: "Nissan) 370Z" },
  { code: "365", label: "Nissan) Cabstar" },
  { code: "352", label: "Nissan) Juke" },
  { code: "348", label: "Nissan) GT-R" },
  { code: "274", label: "Nissan) Tiida Sedan" },
  { code: "355", label: "Nissan) NV2500" },
  { code: "1", label: "Nissan) Versa" },
  { code: "4", label: "Nissan) March" },
  { code: "9", label: "Nissan) Sentra" },
  { code: "23", label: "Nissan) X-Trail" },
  { code: "40", label: "Nissan) Urvan" },
  { code: "197", label: "Nissan) Pathfinder" },
  { code: "179", label: "Nissan) Frontier V6" },
  { code: "189", label: "Nissan) Note" },
  { code: "12", label: "Nissan) Kicks" },
  { code: "379", label: "Nissan) Tsuru" },
  { code: "132", label: "Nissan) Altima" },
  { code: "230", label: "Nissan) Murano" },
  { code: "242", label: "Nissan) Maxima" },
  { code: "3", label: "Nissan) NP300" },
  { code: "150", label: "Peugeot) Rifter" },
  { code: "287", label: "Peugeot) 308" },
  { code: "137", label: "Peugeot) 301" },
  { code: "235", label: "Peugeot) 5008" },
  { code: "216", label: "Peugeot) Expert" },
  { code: "73", label: "Peugeot) Partner" },
  { code: "234", label: "Peugeot) 2008" },
  { code: "223", label: "Peugeot) Manager" },
  { code: "224", label: "Peugeot) 208" },
  { code: "153", label: "Peugeot) 3008" },
  { code: "291", label: "Porsche) Cayman" },
  { code: "310", label: "Porsche) Panamera" },
  { code: "321", label: "Porsche) 718 Boxster" },
  { code: "193", label: "Porsche) Cayenne" },
  { code: "247", label: "Porsche) 911" },
  { code: "246", label: "Porsche) Macan" },
  { code: "221", label: "RAM) 1500" },
  { code: "78", label: "RAM) Promaster" },
  { code: "49", label: "RAM) 700" },
  { code: "43", label: "RAM) Crew Cab" },
  { code: "201", label: "RAM) 2500" },
  { code: "91", label: "RAM) 4000" },
  { code: "237", label: "Range) Rover Evoque" },
  { code: "297", label: "Range) Rover" },
  { code: "202", label: "Range) Rover Sport" },
  { code: "238", label: "Range) Rover Velar" },
  { code: "119", label: "Renault) Koleos" },
  { code: "308", label: "Renault) Twizy" },
  { code: "116", label: "Renault) Captur" },
  { code: "118", label: "Renault) Kangoo" },
  { code: "48", label: "Renault) Duster" },
  { code: "306", label: "Renault) Sandero R.S." },
  { code: "353", label: "Renault) Zoe" },
  { code: "47", label: "Renault) Oroch" },
  { code: "51", label: "Renault) Kwid" },
  { code: "154", label: "Renault) Logan" },
  { code: "100", label: "Renault) Stepway" },
  { code: "360", label: "Renault) Sandero" },
  { code: "97", label: "SEAT) Toledo" },
  { code: "282", label: "SEAT) León ST" },
  { code: "27", label: "SEAT) Ibiza" },
  { code: "81", label: "SEAT) León" },
  { code: "195", label: "SEAT) Tarraco" },
  { code: "77", label: "SEAT) Arona" },
  { code: "149", label: "SEAT) Ateca" },
  { code: "334", label: "Smart) Fortwo" },
  { code: "374", label: "Smart) Forfour" },
  { code: "331", label: "Subaru) WRX" },
  { code: "324", label: "Subaru) BRZ" },
  { code: "191", label: "Subaru) Forester" },
  { code: "210", label: "Subaru) XV" },
  { code: "155", label: "Suzuki) S-Cross" },
  { code: "56", label: "Suzuki) Vitara" },
  { code: "58", label: "Suzuki) Ertiga" },
  { code: "63", label: "Suzuki) Ignis" },
  { code: "33", label: "Suzuki) Swift" },
  { code: "146", label: "Suzuki) Ciaz" },
  { code: "37", label: "Toyota) Avanza" },
  { code: "60", label: "Toyota) Prius" },
  { code: "26", label: "Toyota) Corolla" },
  { code: "105", label: "Toyota) C-HR" },
  { code: "54", label: "Toyota) Hiace" },
  { code: "53", label: "Toyota) Sienna" },
  { code: "95", label: "Toyota) Highlander" },
  { code: "157", label: "Toyota) Yaris R" },
  { code: "14", label: "Toyota) Hilux" },
  { code: "62", label: "Toyota) Prius C" },
  { code: "273", label: "Toyota) Sequoia" },
  { code: "21", label: "Toyota) RAV4" },
  { code: "319", label: "Toyota) GR Supra" },
  { code: "125", label: "Toyota) Yaris Hatchback" },
  { code: "300", label: "Toyota) Land Crusier" },
  { code: "269", label: "Toyota) Tundra" },
  { code: "34", label: "Toyota) Yaris Sedan" },
  { code: "64", label: "Toyota) Tacoma" },
  { code: "83", label: "Toyota) Camry" },
  { code: "30", label: "Volkswagen) Polo" },
  { code: "20", label: "Volkswagen) Tiguan" },
  { code: "10", label: "Volkswagen) Jetta MK7" },
  { code: "5", label: "Volkswagen) Vento" },
  { code: "264", label: "Volkswagen) Golf Variant" },
  { code: "185", label: "Volkswagen) T-Cross" },
  { code: "377", label: "Volkswagen) Pointer" },
  { code: "378", label: "Volkswagen) Bora" },
  { code: "50", label: "Volkswagen) Jetta MK6" },
  { code: "322", label: "Volkswagen) Up" },
  { code: "70", label: "Volkswagen) Virtus" },
  { code: "163", label: "Volkswagen) Crafter" },
  { code: "309", label: "Volkswagen) Touareg" },
  { code: "107", label: "Volkswagen) Amarok" },
  { code: "130", label: "Volkswagen) Teramont" },
  { code: "169", label: "Volkswagen) Gol Sedan" },
  { code: "41", label: "Volkswagen) Saveiro" },
  { code: "170", label: "Volkswagen) Beetle" },
  { code: "86", label: "Volkswagen) Golf" },
  { code: "35", label: "Volkswagen) Gol" },
  { code: "104", label: "Volkswagen) Caddy" },
  { code: "166", label: "Volkswagen) Passat" },
  { code: "69", label: "Volkswagen) Transporter" },
  { code: "341", label: "Volvo) V40" },
  { code: "370", label: "Volvo) S90" },
  { code: "168", label: "Volvo) XC40" },
  { code: "218", label: "Volvo) XC90" },
  { code: "188", label: "Volvo) XC60" },
  { code: "258", label: "Volvo) S60" },
  { code: "376", label: "Otro / Sin especificar" },
] as const;

const AREA_MAP = new Map<string, string>(CAV_AREAS.map((a) => [a.code, a.label]));
const MODEL_MAP = new Map<string, string>(CAV_VEHICLE_MODELS.map((m) => [m.code, m.label]));
const LOT_MAP = new Map<string, string>(CAV_PARKING_LOTS.map((l) => [l.code, l.label]));
const SHIFT_MAP = new Map<string, string>(CAV_SHIFTS.map((s) => [s.code, s.label]));

export function getCavAreaLabel(code: string | null | undefined): string {
  if (!code) return "";
  return AREA_MAP.get(String(code).trim()) ?? String(code).trim();
}

export function getCavVehicleModelLabel(code: string | number | null | undefined): string {
  if (code === null || code === undefined || code === "") return "";
  return MODEL_MAP.get(String(code).trim()) ?? "";
}

export function getCavParkingLotLabel(code: string | null | undefined): string {
  if (!code) return "BASE";
  const normalized = String(code).trim().toUpperCase();
  if (normalized === "BASE" || normalized === "CONFIANZA" || normalized === "VISITANTES") return normalized;
  return LOT_MAP.get(normalized) ?? "BASE";
}

export function getCavParkingLotCode(value: string | null | undefined): "1" | "2" | "3" {
  const v = String(value ?? "1").trim().toUpperCase();
  if (v === "2" || v === "CONFIANZA") return "2";
  if (v === "3" || v === "VISITANTES") return "3";
  return "1";
}

export function getCavShiftLabel(code: string | null | undefined): string {
  if (!code) return "Matutino";
  return SHIFT_MAP.get(String(code).trim().toUpperCase()) ?? String(code).trim();
}
